# Generated by Django 5.2.7 on 2025-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
